openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0

paths:
  /upload:
    post:
      summary: Upload a file
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: strng   # <-- ERROR here
      responses:
        '200':
          description: File uploaded successfully
          content:
            application/json:
              schema:
                type: object
